{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ printf "%s-manager-role" (include "tenant-operator.fullname" .) }}
  labels:
    {{ include "tenant-operator.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - namespaces
      - persistentvolumeclaims
      - secrets
      - serviceaccounts
      - services
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - apps
    resources:
      - daemonsets
      - deployments
      - statefulsets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - batch
    resources:
      - cronjobs
      - jobs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - operator.kubernetes-tenants.org
    resources:
      - tenantregistries
      - tenants
      - tenanttemplates
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - operator.kubernetes-tenants.org
    resources:
      - tenantregistries/finalizers
      - tenants/finalizers
      - tenanttemplates/finalizers
    verbs:
      - update
  - apiGroups:
      - operator.kubernetes-tenants.org
    resources:
      - tenantregistries/status
      - tenants/status
      - tenanttemplates/status
    verbs:
      - get
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ printf "%s-manager-rolebinding" (include "tenant-operator.fullname" .) }}
  labels:
    {{ include "tenant-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ printf "%s-manager-role" (include "tenant-operator.fullname" .) }}
subjects:
  - kind: ServiceAccount
    name: {{ include "tenant-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ printf "%s-leader-election-role" (include "tenant-operator.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "tenant-operator.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ printf "%s-leader-election-rolebinding" (include "tenant-operator.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "tenant-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ printf "%s-leader-election-role" (include "tenant-operator.fullname" .) }}
subjects:
  - kind: ServiceAccount
    name: {{ include "tenant-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- if .Values.metrics.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ printf "%s-metrics-auth-role" (include "tenant-operator.fullname" .) }}
  labels:
    {{ include "tenant-operator.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ printf "%s-metrics-auth-rolebinding" (include "tenant-operator.fullname" .) }}
  labels:
    {{ include "tenant-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ printf "%s-metrics-auth-role" (include "tenant-operator.fullname" .) }}
subjects:
  - kind: ServiceAccount
    name: {{ include "tenant-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ printf "%s-metrics-reader" (include "tenant-operator.fullname" .) }}
  labels:
    {{ include "tenant-operator.labels" . | nindent 4 }}
rules:
  - nonResourceURLs:
      - /metrics
    verbs:
      - get
{{- end }}
{{- end }}
