{{- if .Values.webhook.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tenant-operator.webhookServiceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "tenant-operator.labels" . | nindent 4 }}
  {{- with .Values.webhook.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.webhook.service.type }}
  ports:
    - port: {{ .Values.webhook.service.port }}
      protocol: TCP
      targetPort: {{ .Values.webhook.service.targetPort }}
  selector:
    control-plane: controller-manager
    {{ include "tenant-operator.selectorLabels" . | nindent 4 }}
{{- end }}
