name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please describe your use case and proposed solution.

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature
      placeholder: Describe the feature you'd like to see
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Why do you need this feature? What problem does it solve?
      placeholder: Explain your use case and the problem this would solve
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: How you envision this feature working
      placeholder: Describe how you'd like this feature to work
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other approaches have you considered?
      placeholder: Describe alternative solutions or workarounds you've tried
    validations:
      required: false

  - type: dropdown
    id: willing-to-contribute
    attributes:
      label: Are you willing to contribute this feature?
      description: Would you like to implement this feature yourself?
      options:
        - "Yes, I'd like to contribute"
        - "Maybe, with guidance"
        - "No, just requesting"
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, examples, or references
      placeholder: Add any other context, screenshots, or links
    validations:
      required: false
